name: ci-cd

on:
  push:
    branches: [stage, release]

permissions:
  contents: read

env:
  S3_BUCKET_NAME: test-for-tmp-release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      # 1. Source 단계
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # 2. Build 단계
      # - name: Grant execute permission for gradlew
      #  run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build #-x test
        shell: bash

      # 3. S3 배포 단계
        # 프로젝트 압축
      - name: Make zip file
        run: zip -r ./practice-deploy.zip .
        shell: bash

        # AWS 권한 확인
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

        # 압축한 프로젝트를 S3로 전송
      - name: Upload to S3
        run:
          aws s3 cp --region ap-northeast-2 ./practice-deploy.zip s3://$S3_BUCKET_NAME/practice-deploy.zip

        # Code Deploy 단계
      - name: Code Deploy
        run: aws deploy create-deployment 
          --application-name test
          --deployment-config-name CodeDeployDefault.AllAtOnce 
          --deployment-group-name test
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$practice-deploy.zip

