name: ci-cd

on:
  push:
    branches: [stage, release]

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      # Source 단계
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Build 단계
      # - name: Grant execute permission for gradlew
      #  run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build
        shell: bash

      # S3 배포 단계
      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
        run:
          aws s3 sync \
            -- region ap-northeast-2 \
            build s3://test-for-tmp-release \
            -- delete
        working-directory: ./build

